"""
Copyright (c) 2026, Rick Lan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, and/or sublicense,
for non-commercial purposes only, subject to the following conditions:

- The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
- Commercial use (e.g. use in a product, service, or activity intended to
  generate revenue) is prohibited without explicit written permission from
  the copyright holder.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Dragonpilot longitudinal params.

A lon feature declares its param with `"lon_param": True` on the settings item it
already ships; generate_dp_params.py collects those and writes DP_LON_PARAMS_KEYS
below. plannerd fills DP_LON once at startup:

    DP_LON.update({k: params.get_bool(k) for k in DP_LON_PARAMS_KEYS})

and longitudinal_planner reads it by the same key string the settings file uses:

    from dragonpilot.selfdrive.controls.lib.dp_lon_params import DP_LON
    if DP_LON["dp_lon_acm"]:
      self.a_desired_trajectory = self.acm.update_a_desired_trajectory(...)

This replaces a `class DPFlags` bitmask plus a `dp_flags` argument threaded from
plannerd into LongitudinalPlanner.update(). Both are gone, so plannerd.py keeps a
single fill line and longitudinal_planner.py needs no dp scaffolding at all.

DP_LON["key"], DP_LON.get("key") and `"key" in DP_LON` all agree - see DpParams.

DpParams is imported from opendbc because that is the only layer visible to both
the car and the planner; the class itself is not car-specific.
"""
from opendbc.car.dp_params import DpParams

# DP_LON_PARAMS_BEGIN (generated by generate_dp_params.py - do not edit)
DP_LON_PARAMS_KEYS: tuple[str, ...] = ()
# DP_LON_PARAMS_END

DP_LON = DpParams(DP_LON_PARAMS_KEYS)
