"""
Copyright (c) 2026, Rick Lan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, and/or sublicense,
for non-commercial purposes only, subject to the following conditions:

- The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
- Commercial use (e.g. use in a product, service, or activity intended to
  generate revenue) is prohibited without explicit written permission from
  the copyright holder.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Dragonpilot car params.

The dp params a car interface is allowed to read. A feature declares its param
with `"car_param": True` on the settings item it already ships; generate_dp_params.py
collects those and writes DP_CAR_PARAMS_KEYS below. card.py fills DP_CAR once at startup:

    DP_CAR.update({k: params.get_bool(k) for k in DP_CAR_PARAMS_KEYS})

and a brand interface reads it by the same key string the settings file uses:

    from opendbc.car.dp_params import DP_CAR
    if DP_CAR["dp_toyota_door_auto_lock_unlock"]:
      ret.flags |= ToyotaFlags.LOCK_CTRL.value

This is a dp-owned module rather than an addition to structs.py so that no upstream
file carries the state, and rather than a dp_params argument threaded through
get_params() so that get_car/get_params and all 15 brand interfaces stay
byte-identical to upstream and never conflict on a rebase.

There are deliberately no bit values. An earlier design packed these into a DPFlags
bitmask, which meant every feature hand-picked a bit; five of seven collided on
2**12/2**13 and were hand-renumbered on every rebuild. Keys carry no number, so
nothing can collide.

DP_CAR["key"], DP_CAR.get("key") and `"key" in DP_CAR` all agree: a declared-but-unset
param reads False, an undeclared key raises. See DpParams in opendbc/car/dp_params.py.
"""

# DP_CAR_PARAMS_BEGIN (generated by generate_dp_params.py - do not edit)
DP_CAR_PARAMS_KEYS: tuple[str, ...] = ()
# DP_CAR_PARAMS_END


class DpParams(dict):
  """Reads of a declared-but-unconfigured param return False; reads of an
  undeclared key raise. So docs.py, the car tests and panda_runner work with an
  empty DP_CAR, while a typo or a missing declaration fails loudly instead of
  silently disabling a feature.

  Takes its declared keys explicitly so the same class can back more than one
  param set (see dragonpilot/selfdrive/controls/lib/dp_lon_params.py)."""

  def __init__(self, declared: tuple[str, ...]):
    super().__init__()
    self._declared = declared

  def _check(self, key):
    if key not in self._declared:
      raise KeyError(f"{key!r} is not a declared dp param "
                     f"(add the declaration to its settings item)")

  def __missing__(self, key):
    self._check(key)
    return False

  # dict.get() and `in` do NOT consult __missing__ - they are separate lookups.
  # Left alone, DP.get("declared_key") returns None (not False) and
  # `"declared_key" in DP` returns False whenever the dict has not been filled yet,
  # which silently disables a feature in any process that does not fill it
  # (docs.py, the car tests, panda_runner, plant.py). Override both so every access
  # path agrees with __getitem__.
  def get(self, key, default=None):                    # type: ignore[override]
    self._check(key)
    return super().get(key, False if default is None else default)

  def __contains__(self, key):                          # type: ignore[override]
    return key in self._declared


DP_CAR = DpParams(DP_CAR_PARAMS_KEYS)
