import importlib.util
import shutil
import subprocess
import tempfile
from pathlib import Path

from openpilot.common.test import OpenpilotTestCase

REPO = Path(__file__).resolve().parents[3]
_spec = importlib.util.spec_from_file_location("gen_dp_params", REPO / "generate_dp_params.py")
gcp = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gcp)


def tmp_path():
  d = tempfile.mkdtemp()
  yield Path(d)
  shutil.rmtree(d, ignore_errors=True)


def _write(tmp_path, name, body):
  f = tmp_path / name
  f.write_text(body)
  return f


TEMPLATE = '''# DP_CAR_PARAMS_BEGIN (generated by generate_dp_params.py - do not edit)
DP_CAR_PARAMS_KEYS: tuple[str, ...] = ()
# DP_CAR_PARAMS_END


def other():
  return 42
'''


def _load_dp_params():
  spec = importlib.util.spec_from_file_location(
    "dp_params_probe", REPO / "opendbc_repo" / "opendbc" / "car" / "dp_params.py")
  mod = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(mod)
  return mod


SANDBOX_DP_PARAMS = '''# DP_CAR_PARAMS_BEGIN (generated by generate_dp_params.py - do not edit)
DP_CAR_PARAMS_KEYS: tuple[str, ...] = ()
# DP_CAR_PARAMS_END
'''

SANDBOX_LON_PARAMS = '''# DP_LON_PARAMS_BEGIN (generated by generate_dp_params.py - do not edit)
DP_LON_PARAMS_KEYS: tuple[str, ...] = ()
# DP_LON_PARAMS_END
'''

SANDBOX_UI_PARAMS = '''# DP_UI_PARAMS_BEGIN (generated by generate_dp_params.py - do not edit)
DP_UI_PARAMS: tuple[tuple[str, str], ...] = ()
# DP_UI_PARAMS_END
'''


def _run_sandboxed(tmp_path, body):
  """Run the real script against a throwaway tree; these tests run in parallel."""
  shutil.copy(REPO / "generate_dp_params.py", tmp_path / "generate_dp_params.py")
  settings = tmp_path / "dragonpilot" / "settings"
  settings.mkdir(parents=True)
  (settings / "probe.py").write_text(body)
  car = tmp_path / "opendbc_repo" / "opendbc" / "car"
  car.mkdir(parents=True)
  (car / "dp_params.py").write_text(SANDBOX_DP_PARAMS)
  lon = tmp_path / "dragonpilot" / "selfdrive" / "controls" / "lib"
  lon.mkdir(parents=True)
  (lon / "dp_lon_params.py").write_text(SANDBOX_LON_PARAMS)
  ui = tmp_path / "dragonpilot" / "selfdrive" / "ui"
  ui.mkdir(parents=True)
  (ui / "dp_ui_params.py").write_text(SANDBOX_UI_PARAMS)

  r = subprocess.run(["python3", "generate_dp_params.py"], cwd=tmp_path,
                     capture_output=True, text=True)
  return r, (car / "dp_params.py").read_text(), (ui / "dp_ui_params.py").read_text()


def _load_ui_params():
  spec = importlib.util.spec_from_file_location(
    "dp_ui_params_probe", REPO / "dragonpilot" / "selfdrive" / "ui" / "dp_ui_params.py")
  mod = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(mod)
  return mod


class _FakeParams:
  def __init__(self, values): self._v = values
  def get_bool(self, k): return bool(self._v.get(k, False))
  def get(self, k): return self._v.get(k)


class _Target:
  pass


def _sandbox(tmp_path, settings_body, consumers: dict, ui_state_body=None):
  """Build a throwaway tree and run the real script in it."""
  shutil.copy(REPO / "generate_dp_params.py", tmp_path / "generate_dp_params.py")
  s = tmp_path / "dragonpilot" / "settings"
  s.mkdir(parents=True)
  (s / "probe.py").write_text(settings_body)
  car = tmp_path / "opendbc_repo" / "opendbc" / "car"
  car.mkdir(parents=True)
  (car / "dp_params.py").write_text(SANDBOX_DP_PARAMS)
  lon = tmp_path / "dragonpilot" / "selfdrive" / "controls" / "lib"
  lon.mkdir(parents=True)
  (lon / "dp_lon_params.py").write_text(SANDBOX_LON_PARAMS)
  ui = tmp_path / "dragonpilot" / "selfdrive" / "ui"
  ui.mkdir(parents=True)
  (ui / "dp_ui_params.py").write_text(SANDBOX_UI_PARAMS)
  onroad = tmp_path / "selfdrive" / "ui" / "onroad"
  onroad.mkdir(parents=True)
  for name, body in consumers.items():
    (onroad / name).write_text(body)
  if ui_state_body is not None:
    (tmp_path / "selfdrive" / "ui" / "ui_state.py").write_text(ui_state_body)
  return subprocess.run(["python3", "generate_dp_params.py"], cwd=tmp_path,
                        capture_output=True, text=True)


class TestDpParams(OpenpilotTestCase):

  # --- declaration extraction ---

  def test_extracts_key_marked_as_car_param(self, tmp_path):
    f = _write(tmp_path, "brand-toyota-tss1-sng.py", '''
ITEMS = [
  {"key": "dp_toyota_tss1_sng", "flags": "PERSISTENT", "param_type": "BOOL", "car_param": True},
]
''')
    assert gcp.extract_params(f, "car_param") == [("dp_toyota_tss1_sng", "BOOL")]

  def test_item_without_car_param_is_ignored(self, tmp_path):
    f = _write(tmp_path, "min-feat.ui.rainbow-path.py", '''
ITEMS = [
  {"key": "dp_ui_rainbow", "flags": "PERSISTENT", "param_type": "BOOL"},
]
''')
    assert gcp.extract_params(f, "car_param") == []

  def test_car_param_false_is_ignored(self, tmp_path):
    f = _write(tmp_path, "x.py", 'ITEMS = [{"key": "dp_x", "car_param": False}]\n')
    assert gcp.extract_params(f, "car_param") == []

  def test_file_without_items_returns_empty(self, tmp_path):
    assert gcp.extract_params(_write(tmp_path, "no-items.py", "X = 1\n"), "car_param") == []

  def test_car_param_without_key_raises(self, tmp_path):
    f = _write(tmp_path, "bad.py", 'ITEMS = [{"car_param": True}]\n')
    with self.assertRaisesRegex(ValueError, "no key"):
      gcp.extract_params(f, "car_param")

  def test_non_bool_car_param_raises(self, tmp_path):
    """card.py reads these with get_bool, so a non-BOOL would be silently wrong."""
    f = _write(tmp_path, "bad2.py", '''
ITEMS = [{"key": "dp_x", "param_type": "INT", "car_param": True}]
''')
    with self.assertRaisesRegex(ValueError, "BOOL"):
      gcp.extract_params(f, "car_param")

  # --- rendering ---

  def test_render_region_is_valid_python_and_sorted(self):
    body = gcp.render_region((("dp_a", "BOOL"), ("dp_b", "BOOL")), "DP_CAR_PARAMS_KEYS", "keys")
    ns: dict = {}
    exec(body, ns)
    assert ns["DP_CAR_PARAMS_KEYS"] == ("dp_a", "dp_b")

  def test_render_empty_region_is_an_empty_tuple(self):
    ns: dict = {}
    exec(gcp.render_region((), "DP_CAR_PARAMS_KEYS", "keys"), ns)
    assert ns["DP_CAR_PARAMS_KEYS"] == ()

  def test_update_region_replaces_and_preserves_surroundings(self, tmp_path):
    f = tmp_path / "dp_params.py"
    f.write_text(TEMPLATE)
    gcp.update_region(f, "DP_CAR_PARAMS", gcp.render_region((("dp_a", "BOOL"),), "DP_CAR_PARAMS_KEYS", "keys"))
    out = f.read_text()
    assert '"dp_a",' in out
    assert "def other():" in out
    assert out.count("DP_CAR_PARAMS_BEGIN") == 1

  def test_update_region_is_idempotent(self, tmp_path):
    f = tmp_path / "dp_params.py"
    f.write_text(TEMPLATE)
    body = gcp.render_region((("dp_a", "BOOL"),), "DP_CAR_PARAMS_KEYS", "keys")
    gcp.update_region(f, "DP_CAR_PARAMS", body)
    first = f.read_text()
    gcp.update_region(f, "DP_CAR_PARAMS", body)
    assert f.read_text() == first

  def test_update_region_does_not_accumulate_stale_keys(self, tmp_path):
    f = tmp_path / "dp_params.py"
    f.write_text(TEMPLATE)
    gcp.update_region(f, "DP_CAR_PARAMS", gcp.render_region((("dp_a", "BOOL"),), "DP_CAR_PARAMS_KEYS", "keys"))
    gcp.update_region(f, "DP_CAR_PARAMS", gcp.render_region((("dp_b", "BOOL"),), "DP_CAR_PARAMS_KEYS", "keys"))
    out = f.read_text()
    assert "dp_b" in out and "dp_a" not in out

  def test_update_region_missing_marker_raises(self, tmp_path):
    f = tmp_path / "dp_params.py"
    f.write_text("nothing here\n")
    with self.assertRaisesRegex(ValueError, "DP_CAR_PARAMS_BEGIN"):
      gcp.update_region(f, "DP_CAR_PARAMS", "DP_CAR_PARAMS_KEYS = ()\n")

  # --- the DpParams shared-state object ---

  def test_declared_but_unset_param_reads_false(self):
    """docs.py, the car tests and panda_runner all run with an unpopulated DP."""
    dp = _load_dp_params().DpParams(("dp_declared",))
    assert dp["dp_declared"] is False

  def test_undeclared_param_raises(self):
    """A typo or a missing declaration must fail loudly, not silently disable."""
    dp = _load_dp_params().DpParams(("dp_declared",))
    with self.assertRaisesRegex(KeyError, "not a declared dp param"):
      dp["dp_typoed"]

  def test_populated_value_is_returned(self):
    dp = _load_dp_params().DpParams(("dp_declared",))
    dp.update({"dp_declared": True})
    assert dp["dp_declared"] is True

  def test_two_param_sets_are_independent(self):
    """The car dict and the lon dict must not validate against each other's keys."""
    mod = _load_dp_params()
    car = mod.DpParams(("dp_car_only",))
    lon = mod.DpParams(("dp_lon_only",))
    assert car["dp_car_only"] is False
    assert lon["dp_lon_only"] is False
    with self.assertRaises(KeyError):
      car["dp_lon_only"]
    with self.assertRaises(KeyError):
      lon["dp_car_only"]

  # --- build behaviour: SConstruct aborts the build on a non-zero exit ---

  def test_build_succeeds_and_writes_the_key(self, tmp_path):
    r, src, _ = _run_sandboxed(
      tmp_path, 'ITEMS = [{"key": "dp_probe", "param_type": "BOOL", "car_param": True}]\n')
    assert r.returncode == 0, r.stdout + r.stderr
    assert '"dp_probe",' in src
    assert "1 car_params" in r.stdout

  def test_build_fails_on_car_param_without_key(self, tmp_path):
    r, _, _ = _run_sandboxed(tmp_path, 'ITEMS = [{"car_param": True}]\n')
    assert r.returncode != 0, r.stdout + r.stderr
    assert "no key" in r.stdout

  def test_build_fails_on_non_bool_car_param(self, tmp_path):
    r, _, _ = _run_sandboxed(
      tmp_path, 'ITEMS = [{"key": "dp_x", "param_type": "INT", "car_param": True}]\n')
    assert r.returncode != 0, r.stdout + r.stderr
    assert "BOOL" in r.stdout

  def test_build_succeeds_with_no_declarations(self, tmp_path):
    r, src, _ = _run_sandboxed(tmp_path, 'ITEMS = []\n')
    assert r.returncode == 0, r.stdout + r.stderr
    assert "DP_CAR_PARAMS_KEYS: tuple[str, ...] = ()" in src

  # --- ui params: pairs shape, and INT is allowed unlike car/lon ---

  def test_ui_param_allows_non_bool(self, tmp_path):
    f = _write(tmp_path, "min-feat.ui.lead-stats.py",
               'ITEMS = [{"key": "dp_ui_lead", "param_type": "INT", "ui_param": True}]\n')
    assert gcp.extract_params(f, "ui_param") == [("dp_ui_lead", "INT")]

  def test_render_pairs_shape_carries_the_type(self):
    body = gcp.render_region(
      (("dp_ui_lead", "INT"), ("dp_ui_rainbow", "BOOL")), "DP_UI_PARAMS", "pairs")
    ns: dict = {}
    exec(body, ns)
    assert ns["DP_UI_PARAMS"] == (("dp_ui_lead", "INT"), ("dp_ui_rainbow", "BOOL"))

  def test_render_pairs_requires_a_type(self):
    with self.assertRaisesRegex(ValueError, "param_type"):
      gcp.render_region((("dp_x", None),), "DP_UI_PARAMS", "pairs")

  def test_apply_sets_attributes_named_after_the_param_key(self):
    """Existing consumers read self.dp_ui_rainbow etc, so the names must not change."""
    mod = _load_ui_params()
    mod.DP_UI_PARAMS = (("dp_ui_rainbow", "BOOL"), ("dp_ui_lead", "INT"))
    t = _Target()
    assert mod.apply_dp_ui_params(t, _FakeParams({"dp_ui_rainbow": True, "dp_ui_lead": "2"})) == 2
    assert t.dp_ui_rainbow is True
    assert t.dp_ui_lead == 2

  def test_apply_uses_zero_for_unset_int(self):
    mod = _load_ui_params()
    mod.DP_UI_PARAMS = (("dp_ui_lead", "INT"),)
    t = _Target()
    mod.apply_dp_ui_params(t, _FakeParams({}))
    assert t.dp_ui_lead == 0

  def test_apply_with_no_declarations_sets_nothing(self):
    mod = _load_ui_params()
    mod.DP_UI_PARAMS = ()
    t = _Target()
    assert mod.apply_dp_ui_params(t, _FakeParams({})) == 0

  def test_build_writes_ui_pairs(self, tmp_path):
    r, _, ui_src = _run_sandboxed(
      tmp_path, 'ITEMS = [{"key": "dp_ui_lead", "param_type": "INT", "ui_param": True}]\n')
    assert r.returncode == 0, r.stdout + r.stderr
    assert '("dp_ui_lead", "INT"),' in ui_src
    assert "1 ui_params" in r.stdout

  # --- consumer check: every consumed dp param must have a provider ---

  def test_undeclared_ui_attribute_fails_the_build(self, tmp_path):
    """The exact failure a rebase produces: setter dropped, consumer survives."""
    r = _sandbox(tmp_path, "ITEMS = []\n", {"r.py": "if ui_state.dp_ui_rainbow:\n  pass\n"})
    assert r.returncode != 0, r.stdout
    assert "dp_ui_rainbow is read but nothing provides it" in r.stdout

  def test_undeclared_dict_key_fails_the_build(self, tmp_path):
    r = _sandbox(tmp_path, "ITEMS = []\n", {"c.py": 'if DP_CAR["dp_lat_alka"]:\n  pass\n'})
    assert r.returncode != 0, r.stdout
    assert 'DP_CAR["dp_lat_alka"] is read but never declared' in r.stdout

  def test_declared_consumer_passes(self, tmp_path):
    r = _sandbox(tmp_path,
                 'ITEMS = [{"key": "dp_ui_rainbow", "param_type": "BOOL", "ui_param": True},\n'
                 + '         {"key": "dp_lat_alka", "param_type": "BOOL", "car_param": True}]\n',
                 {"r.py": 'if ui_state.dp_ui_rainbow:\n  pass\n',
                  "c.py": 'if DP_CAR["dp_lat_alka"]:\n  pass\n'})
    assert r.returncode == 0, r.stdout + r.stderr

  def test_assigned_attribute_needs_no_declaration(self, tmp_path):
    """Feature frame state (dp_alka_active) is assigned, not a declared param."""
    r = _sandbox(tmp_path, "ITEMS = []\n",
                 {"r.py": "if ui_state.dp_alka_active:\n  pass\n"},
                 ui_state_body="class UIState:\n  def __init__(self):\n    self.dp_alka_active = False\n")
    assert r.returncode == 0, r.stdout + r.stderr

  def test_provider_module_docstrings_are_not_treated_as_consumers(self, tmp_path):
    """dp_params.py/dp_lon_params.py show usage examples in their docstrings."""
    r = _sandbox(tmp_path, "ITEMS = []\n", {})
    assert r.returncode == 0, r.stdout + r.stderr

  # --- every access path must agree (dict.get/`in` bypass __missing__ by default) ---

  def test_get_matches_getitem_for_declared_but_unset(self):
    """DP.get() must return False, not None - a None would silently disable a feature
    in any process that does not fill the dict (docs.py, car tests, panda_runner)."""
    dp = _load_dp_params().DpParams(("dp_declared",))
    assert dp["dp_declared"] is False
    assert dp.get("dp_declared") is False

  def test_get_raises_on_undeclared(self):
    dp = _load_dp_params().DpParams(("dp_declared",))
    with self.assertRaisesRegex(KeyError, "not a declared dp param"):
      dp.get("dp_typoed")

  def test_contains_reports_declaration_not_fill_state(self):
    dp = _load_dp_params().DpParams(("dp_declared",))
    assert "dp_declared" in dp          # declared, though unset
    assert "dp_typoed" not in dp

  def test_get_returns_value_once_filled(self):
    dp = _load_dp_params().DpParams(("dp_declared",))
    dp.update({"dp_declared": True})
    assert dp.get("dp_declared") is True

  def test_explicit_default_still_honoured(self):
    dp = _load_dp_params().DpParams(("dp_declared",))
    assert dp.get("dp_declared", "sentinel") == "sentinel"

  # --- AST guard: sees what python sees ---

  def test_guard_catches_undeclared_get_call(self, tmp_path):
    r = _sandbox(tmp_path, "ITEMS = []\n", {"c.py": 'if DP_CAR.get("dp_lat_alka"):\n  pass\n'})
    assert r.returncode != 0, r.stdout
    assert 'DP_CAR["dp_lat_alka"] is read but never declared' in r.stdout

  def test_guard_catches_undeclared_in_test(self, tmp_path):
    r = _sandbox(tmp_path, "ITEMS = []\n", {"c.py": 'if "dp_lat_alka" in DP_CAR:\n  pass\n'})
    assert r.returncode != 0, r.stdout

  def test_guard_ignores_comments_and_strings(self, tmp_path):
    """A regex scan flagged these; the AST scan sees them for what they are."""
    body = (
      '# if DP_CAR["dp_not_real"]: pass\n'
      + 'DOC = \'\'\'example: DP_CAR["dp_also_not_real"]\'\'\'\n'
    )
    r = _sandbox(tmp_path, "ITEMS = []\n", {"c.py": body})
    assert r.returncode == 0, r.stdout + r.stderr

  def test_guard_reports_non_literal_subscript_as_note_not_error(self, tmp_path):
    r = _sandbox(tmp_path, "ITEMS = []\n", {"c.py": 'k = "dp_x"\nif DP_CAR[k]:\n  pass\n'})
    assert r.returncode == 0, r.stdout + r.stderr
    assert "cannot be checked" in r.stdout
