from openpilot.system.ui.lib.multilang import (
  multilang as base_multilang,
  PLURAL_SELECTORS,
  TRANSLATIONS_DIR,
  load_translations,
  tr_noop,
)


class DpMultilang:
  """Wrapper that syncs with base multilang and adds dragonpilot translations."""

  def __init__(self):
    self._translations: dict[str, str] = {}
    self._plurals: dict[str, list[str]] = {}
    self._plural_selector = PLURAL_SELECTORS.get('en', lambda n: 0)
    self._loaded_language: str = ""

  @property
  def languages(self):
    """Delegate to base multilang."""
    return base_multilang.languages

  @property
  def language(self):
    """Delegate to base multilang."""
    return base_multilang.language

  def _ensure_loaded(self):
    """Reload dragon translations if base language changed.

    Reads the .po directly, like the base module does. .mo is gitignored and nothing
    in the build compiles one, so it is never present on a device.
    """
    current_lang = base_multilang.language
    if current_lang == self._loaded_language:
      return
    self._loaded_language = current_lang
    try:
      po_path = TRANSLATIONS_DIR.joinpath(f'dragonpilot_{current_lang}.po')
      self._translations, self._plurals = load_translations(po_path)
    except FileNotFoundError:
      self._translations, self._plurals = {}, {}
    self._plural_selector = PLURAL_SELECTORS.get(current_lang, lambda n: 0)

  def tr(self, text: str) -> str:
    self._ensure_loaded()
    return self._translations.get(text) or base_multilang.tr(text)

  def trn(self, singular: str, plural: str, n: int) -> str:
    self._ensure_loaded()
    forms = self._plurals.get(singular)
    if forms:
      idx = self._plural_selector(n)
      if idx < len(forms) and forms[idx]:
        return forms[idx]
    return base_multilang.trn(singular, plural, n)


def dp_translation_chars(code: str) -> set[str]:
  """Characters used by dragonpilot's own translations, for font glyph subsetting.

  dragonpilot_*.po is generated by update_translations.py and may not exist for
  every language, so a missing file must not be fatal.
  """
  try:
    return set(TRANSLATIONS_DIR.joinpath(f'dragonpilot_{code}.po').read_text(encoding='utf-8'))
  except FileNotFoundError:
    return set()


multilang = DpMultilang()

tr, trn = multilang.tr, multilang.trn

__all__ = ['multilang', 'tr', 'trn', 'tr_noop', 'TRANSLATIONS_DIR', 'dp_translation_chars']
