from dragonpilot.settings import tr

ITEMS = [
  {
    "section": "Lateral",
    "key": "dp_lat_alka",
    "needs_restart": True,
    "type": "toggle_item",
    "title": lambda: tr("Always-on Lane Keeping Assist (ALKA)"),
    "description": lambda: tr("Enable lateral control even when ACC/cruise is disengaged, using ACC Main or LKAS button to toggle. Vehicle must be moving."),
    "brands": ["toyota", "hyundai", "honda", "volkswagen", "subaru", "mazda", "nissan", "ford"],
    "flags": "PERSISTENT",
    "param_type": "BOOL",
    "default": "0",
    "car_param": True,
  },
  {
    "section": "Lateral",
    "key": "dp_lat_alka_min_speed",
    "needs_restart": True,
    "type": "spin_button_item",
    "title": lambda: tr("ALKA Minimum Enable Speed"),
    "description": lambda: tr("ALKA only activates at or above this speed. Off = no minimum."),
    "depends_on": "dp_lat_alka",
    "brands": ["toyota", "hyundai", "honda", "volkswagen", "subaru", "mazda", "nissan", "ford"],
    "unit": "speed",
    "min_val": 0,
    "max_val": 30,
    "step": 5,
    "special_value_text": lambda: tr("Off"),
    "default": 0,
    "flags": "PERSISTENT",
    "param_type": "INT",
  },
]
