"""
Copyright (c) 2026, Rick Lan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, and/or sublicense,
for non-commercial purposes only, subject to the following conditions:

- The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
- Commercial use (e.g. use in a product, service, or activity intended to
  generate revenue) is prohibited without explicit written permission from
  the copyright holder.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Dragonpilot UI params.

A UI feature declares its param with `"ui_param": True` on the settings item it
already ships; generate_dp_params.py collects those into DP_UI_PARAMS below, and
ui_state.py applies them in one call:

    apply_dp_ui_params(self, self.params)

Each param becomes an attribute on UIState named exactly after the param key, so
existing consumers keep reading self.dp_ui_rainbow, self.dp_ui_lead and friends
unchanged. That is why this is setattr onto an object that already exists rather
than a DP_UI dict like the car and lon sides -- UIState is already the UI's shared
state, and renaming every consumer would cost far more than it saves.

Unlike car/lon params these are not BOOL-only: the UI has INT params (speeds,
display modes), so the generated table carries the type alongside the key.

Features keep any state that is not a plain param read -- derived values, per-frame
state -- in their own code; only the declaration is generated.
"""

# DP_UI_PARAMS_BEGIN (generated by generate_dp_params.py - do not edit)
DP_UI_PARAMS: tuple[tuple[str, str], ...] = ()
# DP_UI_PARAMS_END


def apply_dp_ui_params(obj, params) -> int:
  """setattr one attribute per declared param, named exactly after the param key.

  Returns the count applied. Unknown types fall back to the raw string value."""
  n = 0
  for key, ptype in DP_UI_PARAMS:
    if ptype == "BOOL":
      value = params.get_bool(key)
    elif ptype == "INT":
      value = int(params.get(key) or 0)
    elif ptype == "FLOAT":
      value = float(params.get(key) or 0.0)
    else:
      value = params.get(key)
    setattr(obj, key, value)
    n += 1
  return n
